# Generated by Django 4.2.3 on 2023-09-11 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "world_type",
                    models.CharField(
                        choices=[
                            ("universe", "Universe"),
                            ("planet", "Planet"),
                            ("continent", "Continent"),
                            ("empire", "Empire"),
                            ("country", "Country"),
                            ("kingdom", "Kingdom"),
                            ("state", "State"),
                            ("region", "Region"),
                            ("city", "City"),
                            ("town", "Town"),
                        ],
                        default="kingdom",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("desription", models.TextField()),
                ("attributes", models.TextField()),
                (
                    "world",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worlds.world",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MagicSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "world",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worlds.world",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("desription", models.TextField()),
                ("attributes", models.TextField()),
                (
                    "landscape_type",
                    models.CharField(
                        choices=[
                            ("forest", "Forest"),
                            ("island", "Island"),
                            ("sea", "Sea"),
                            ("river", "River"),
                            ("ocean", "Ocean"),
                            ("mountain", "Mountain"),
                            ("desert", "Desert"),
                            ("plains", "Plains"),
                        ],
                        default="plains",
                        max_length=32,
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worlds.world",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("nickname", models.CharField(max_length=128)),
                (
                    "character_type",
                    models.CharField(
                        choices=[
                            ("protagonist", "Protagonist"),
                            ("antagonist", "Antagonist"),
                            ("side_kick", "Side Kick"),
                            ("love_interest", "Love Interest"),
                            ("mentor", "Mentor"),
                            ("ally", "Ally"),
                            ("spirit", "Spirit"),
                            ("human", "Human"),
                            ("non_human", "Non-Human"),
                            ("animal", "Animal"),
                            ("monster", "Monster"),
                        ],
                        default="human",
                        max_length=32,
                    ),
                ),
                ("bio", models.TextField()),
                ("attributes", models.TextField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
